### ISSUE TITLE
parameters of instance not visible;

### ISSUE THREAD

**Issue by hannesrichter** [koi-learning/koi-pwa#18] opened 2021-01-22 19:56 UTC
Parameters are not shown in the instance view.
Model parameters are visualized correctly.

The following error was shown in the developer console:
```
Uncaught (in promise) TypeError: Cannot read property 'instance_uuid' of undefined
    at bundle.js:1601
    at bundle.js:1601
    at Array.filter (<anonymous>)
    at xu (bundle.js:1601)
    at Au (bundle.js:1601)
    at HTMLElement.stateChanged (bundle.js:1727)
    at bundle.js:1601
    at h (bundle.js:1550)
    at bundle.js:1550
    at dispatch (bundle.js:1550)```

**Comment by hannesrichter** [comment] 2021-01-24 10:08
This behavior is not reproducible every time. It seems only the first instance ever created has this problem. However, the logged error remains.

**Comment by jonau** [comment] 2021-01-27 10:48
The error is unrelated to the problem and has no side-effect. It will be fixed with one of my next commits.

But I cannot reproduce the behavior for the parameters.
Can you provide a model where this behavior is seen?

**Closed as completed** 2021-05-04 09:37 UTC
Labels: bug
